### login user
POST localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin"
}
> {%
    client.global.set("token", response.body.token)
    client.global.set("id", response.body.user.id)
%}

### get all bookings
GET localhost:8080/api/bookings

### get all bookings by vehicle
GET localhost:8080/api/bookings/vehicle/1

### get all bookings by user
GET localhost:8080/api/bookings/user/1

### get all bookings by status open
GET localhost:8080/api/bookings/status/OPEN

### get all bookings by status confirmed
GET localhost:8080/api/bookings/status/CONFIRMED

### get all bookings by status canceled
GET localhost:8080/api/bookings/status/CANCELED

### get the first booking
GET localhost:8080/api/bookings/1

### create a booking
POST localhost:8080/api/bookings
Content-Type: application/json

{
  "days": 2,
  "userId": 2,
  "vehicleId": 2
}

### update the vehicle on booking
PUT localhost:8080/api/bookings/1/vehicle/2

### cancel booking
PUT localhost:8080/api/bookings/1/cancel
Authorization: Bearer {{token}}

### confirm booking
PUT localhost:8080/api/bookings/1/confirm
Authorization: Bearer {{token}}

### delete the first booking
DELETE localhost:8080/api/bookings/1
Authorization: Bearer {{token}}