### create a user
POST localhost:8080/api/users
Content-Type: application/json

{
  "name": "Thiago You",
  "email": "thiago.you@pucpr.com",
  "password": "password"
}

### get all users
GET localhost:8080/api/users

### get the first user
GET localhost:8080/api/users/1

### delete the first user
DELETE localhost:8080/api/users/1

### grant role to user
POST localhost:8080/api/users/1/role/ADMIN
Content-Type: application/json

{
  "id": 1,
  "role": "Admin"
}
