### login user
POST localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin"
}
> {%
    client.global.set("token", response.body.token)
    client.global.set("id", response.body.user.id)
%}

### get all users
GET localhost:8080/api/users

### get all users order by desc
GET localhost:8080/api/users?sortDir=desc

### get all users order by desc and with role ADMIN
GET localhost:8080/api/users?sortDir=desc&role=ADMIN

### get the first user
GET localhost:8080/api/users/1

### create a user
POST localhost:8080/api/users
Content-Type: application/json

{
  "name": "Thiago You",
  "email": "thiago.you@pucpr.com",
  "password": "password"
}

### grant role to user
PUT localhost:8080/api/users/2/roles/ADMIN

### delete the first user
DELETE localhost:8080/api/users/1
Authorization: Bearer {{token}}